import pytest

from apps.articles.models import Article

pytestmark = pytest.mark.django_db


def test_slug_is_autogenerated(category, user):
    article = Article.objects.create(
        title="Hello World", content="x", category=category, author=user
    )
    assert article.slug == "hello-world"


def test_slugs_are_unique(category, user):
    a = Article.objects.create(title="Dup", content="x", author=user)
    b = Article.objects.create(title="Dup", content="y", author=user)
    assert a.slug != b.slug
    assert b.slug.startswith("dup-")


def test_read_time_minimum_one_minute(user):
    article = Article.objects.create(title="Tiny", content="one word", author=user)
    assert article.read_time == 1


def test_category_slug(category):
    assert category.slug == "programming"


def test_str_methods(article, category):
    assert str(category) == "Programming"
    assert str(article) == "Django"
